// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbA_8pl5bonrr3h5iTp3qRt2mmaFuZb84',
    appId: '1:20917329736:web:3367b864a5e9c274359d7d',
    messagingSenderId: '20917329736',
    projectId: 'firesamplechatt',
    authDomain: 'firesamplechatt.firebaseapp.com',
    storageBucket: 'firesamplechatt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaqvxpR2fT7o3UAMuda4TRdGAx0SrKKTg',
    appId: '1:20917329736:android:4d4b1313887f1f58359d7d',
    messagingSenderId: '20917329736',
    projectId: 'firesamplechatt',
    storageBucket: 'firesamplechatt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Xsapk-ctClBWq7CfhZU3YX_fjdcp25A',
    appId: '1:20917329736:ios:a1538216271362e1359d7d',
    messagingSenderId: '20917329736',
    projectId: 'firesamplechatt',
    storageBucket: 'firesamplechatt.appspot.com',
    iosClientId: '20917329736-6mfdefosb9cn31u8spboc0tcoaj5bgj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttersample1',
  );
}
